# Generated by Django 4.1.7 on 2023-03-12 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0003_productos'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompraOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_orden_compra', models.CharField(max_length=255)),
                ('precio_producto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('correo_proveedor', models.EmailField(editable=False, max_length=254)),
                ('direccion_proveedor', models.TextField(editable=False)),
                ('tax_id', models.CharField(editable=False, max_length=50)),
                ('ciudad_proveedor', models.CharField(editable=False, max_length=100)),
                ('nombre_contacto_proveedor', models.CharField(editable=False, max_length=100)),
                ('numero_contacto_proveedor', models.CharField(editable=False, max_length=20)),
                ('metodo_entrega_proveedor', models.CharField(editable=False, max_length=100)),
                ('upc', models.CharField(editable=False, max_length=255)),
                ('sku', models.CharField(editable=False, max_length=255)),
                ('nombre_producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.productos')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.vendor')),
            ],
        ),
    ]
