# Generated by Django 4.1.7 on 2023-03-13 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_compraorden'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductosProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('proveedor', models.CharField(max_length=100)),
                ('precio', models.IntegerField()),
                ('cantidad_disponible', models.IntegerField()),
                ('upc', models.IntegerField()),
            ],
        ),
    ]
