# Generated by Django 4.1.7 on 2023-03-13 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_productosproveedor'),
    ]

    operations = [
        migrations.CreateModel(
            name='NuevoModelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='Nombre predefinido', max_length=100)),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('precio', models.IntegerField(blank=True, null=True)),
                ('cantidad_disponible', models.IntegerField(blank=True, null=True)),
                ('upc', models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
